### ISSUE TITLE
RTL titles should align right.

### ISSUE THREAD

**Issue by alonidel** [obahareth/notion-rtl#12]
Titles should align right.

It looks like this:
![Screen Shot 2020-08-28 at 23 05 27](https://user-images.githubusercontent.com/47115834/91611103-24773080-e983-11ea-8a85-2c6f7bcd240c.png)

And should look like this:
![Screen Shot 2020-08-28 at 23 06 59](https://user-images.githubusercontent.com/47115834/91611120-348f1000-e983-11ea-8f38-5f45f94c8ec4.png)

**Comment by obahareth** [comment]
@alonidel This should be resolved in #19, (which is version 1.3.0, it will be auto-released once Google is done reviewing it).
