### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by mr-islam** [obahareth/notion-rtl#17]
Hi, thank you for this wonderful utility!

I just wanted to leave a request for a Firefox version of this extension—hopefully that will be smooth because both are on the WebExtensions API and I think just the namespace changes for some parts of the API (ie. using `browser` instead of `chrome`)

**Comment by mehrad77** [comment]
I hope someone can publish this for firefox too

**Comment by fh222333A** [comment]
got it to work on firefox, its the same exact code but modified the manifest.json to make it work on firefox.

**Comment by Fahme** [comment]
You can clone the repo to your machine load the manifest.json as it is (no need to change anything) in Firefox and the extension should work fine, until @obahareth release a version into the stores, this is the only work around.

**Comment by fh222333A** [comment]
for me firefox wouldn't install the package unless i added a min version and an id in the manifest.json

**Comment by Fahme** [comment]
https://addons.mozilla.org/en-US/firefox/addon/notion-rtl/

Realsed gonna close this.
