### ISSUE TITLE
Avoid polling and listen for node additions

### ISSUE THREAD

**Issue by obahareth** [obahareth/notion-rtl#2]
The only reason we keep polling right now is to make sure that newly added blocks are RTL-styled, it would be faster/better to watch DOM node updates/additions somehow and apply our styling on the new nodes only.

(We also need to poll only once until `.notion-page-content` exists, even if we remove the continuous polling, we should keep the polling for the this part then clear out the handler).

**Comment by Fahme** [comment]
Hey @obahareth thanks for working on this great stuff !

Did you try using a Mutation observer instead of polling ? 
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

if not this should be an easy fix probably i can help with :)

**Comment by obahareth** [comment]
Hey @Fahme, yep a friend suggested that right when I launched this mod, I just never got around to doing it. If you think you can take a shot at it that would be wonderful!

**Comment by Fahme** [comment]
Sure i would love to help, but after the latest release 1.1.0 the extension don't seem to work anymore ? i've downloaded both the store and GH version and can't seem to get notion page to be on the right. My current OS is macOS Catalina (10.15) and my OS lang is set to Arabic.

Note : the extension did work previously for me on the older versions.
