### ISSUE TITLE
RTL on toggle list

### ISSUE THREAD

**Issue by itayz1230** [obahareth/notion-rtl#23]
right to left does not work on toggle list... Don't know how to solve it but it will be helpful if someone can :)

**Comment by Fahme** [comment]
Will look into it thanks for the suggestion

**Comment by Fahme** [comment]
Thanks for the feature request, i tested the extension and the only issue i found was that list's title are the only ones that are not supported. 

Here's an example : https://spectrum-dance-b2d.notion.site/Toggle-List-fb95567774c6408c961eca6e5c9de39f

the main title is not aligned to the right but the list in the toggle actually are aligned.

So the current issue is that, you want support for toggle list title to be on the right when using a RTL lang, correct ?

**Comment by manssorr** [comment]
> Thanks for the feature request, i tested the extension and the only issue i found was that list's titles are the only ones that are not supported.
> 
> Here's an example : https://spectrum-dance-b2d.notion.site/Toggle-List-fb95567774c6408c961eca6e5c9de39f
> 
> the main title is not aligned to the right but the list actually are aligned.
> 
> So the current issue is that, you want support for the toggle lists titles to be on the right when using an RTL lang, correct ?

Yeah this is the problem, when title is English and you wanna write inside toggle in Arabic.

**Comment by dragonwocky** [comment]
p.s. this is fixed in https://github.com/notion-enhancer/repo/blob/dev/right-to-left/client.mjs
