### ISSUE TITLE
Notion rtl not working 

### ISSUE THREAD

**Issue by AhmedMub** [obahareth/notion-rtl#29]
# Notion RTL stopped working
I tried removing and readd the extension to chrome browser but It's not working.

![image](https://user-images.githubusercontent.com/32661307/146670399-896df8bd-9f3a-48ce-9f25-ae4657efb8d9.png)

Please Help..
Thank you!

**Comment by Fahme** [comment]
can you confirm if its working on these pages ?

https://www.notion.so/Pages-f2cfdcc28e074a04b40bed5fea7ba4d5

**Comment by AhmedMub** [comment]
Yes, It is not working @Fahme 

![image](https://user-images.githubusercontent.com/32661307/146672451-54866bb1-12af-493f-95ff-1762a29ea81f.png)

**Comment by Fahme** [comment]
Thanks @AhmedMub can one last thing, can you provide me with the chrome + nortion rtl versions you're using

**Comment by AhmedMub** [comment]
Chrome is: 96.0.4664.110,
Notion RTL: 1.4.0
Thanks, @Fahme for helping

**Comment by AhmedMub** [comment]
please help @obahareth

**Comment by Fahme** [comment]
I'm using the same versions and it's working fine for me. 

One possible way to help us debug it is to:
- start a new chrome profile with not extensions 
- download notion rtl 
- test these pages on it https://www.notion.so/Pages-f2cfdcc28e074a04b40bed5fea7ba4d5


There's a possibility that other extensions you have are affecting notion-rtl

**Comment by obahareth** [comment]
@Fahme @AhmedMub It's not working for me either, I don't see a clear cause but could #28 be related? I am seeing a lot of these.

**Comment by Fahme** [comment]
There are changes made to notion i believe i need to dig deeper into that,  but what's even more weird is that the extension is working fine for me.

![Screen Shot 2021-12-20 at 9 26 08 PM](https://user-images.githubusercontent.com/10753722/146821709-7078b91f-0e12-4b88-8c5b-a0a416c0e17b.png)
 
I wonder if your latest changes had any effects though https://github.com/obahareth/notion-rtl/commit/c65bdc7ebf27d336807a447615aedbdaeb8c8f75 

@obahareth

**Comment by Fahme** [comment]
@obahareth @AhmedMub if you can help me out with screenshots from console dev tools, for any errors that would be awesome.

**Comment by obahareth** [comment]
Closing this in to continue discussion in #28 

I added a screenshot there.
