### ISSUE TITLE
Find a way to make this work in the desktop apps

### ISSUE THREAD

**Issue by obahareth** [obahareth/notion-rtl#3]
I tried making [a script](https://gist.github.com/obahareth/aad61b3a744201ebd0f087238e4794da) in Go that includes the script in `~/Library/"Application Support"/Notion/assetCache/{version}/index-*.html` (on macOS) and it works, however that file gets deleted when relaunching Notion. I also tried unpacking the app.asar from inside `/Applications/Notion.app` and including that script in `renderer/index.html` (and even just tossing an H1 there), but it appears that HTML file is only used when launching the app and then a new one is downloaded from the website.

Here's the script tag for reference

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/obahareth/notion-rtl@master/index.js"></script>
```

Approaches I'm considering:
- Unpack the app.asar, modify the JS to somehow inject the script tag and persist that change across the index.html changes.
- Making a daemon in Go that watches changes to the `Application Support/Notion/assetCache` directory and re-inject the tag as necessary.

**Comment by obahareth** [comment]
I'm thinking of making a daemon using [systray](https://github.com/getlantern/systray) and having it run automatically on startup (with options to disable that from the menubar icon)

**Comment by dragonwocky** [comment]
Hey!

I work on the notion-enhancer, a script that mods the desktop app to add custom theming and scripting (e.g. a hotkey to toggle window visibility). I'm working on transitioning it from a simple mod to a proper mod-loader, and I was hoping to be able to include this as a mod (you'd be properly attributed for it, of course).

If that's alright with you, please let me know as soon as possible so I can make this something as many notion users can benefit from as possible :)

**Comment by obahareth** [comment]
Hey @dragonwocky, thanks a lot for that, that would be wonderful! I'd love to have this mod included there!

**Comment by dragonwocky** [comment]
Implemented/working and will be included in the update once in released in a couple days!

Including the improvements from #11 and simplified a bit to remove unnecessary code, it all boils down to this: https://github.com/dragonwocky/notion-enhancer/blob/js/mods/right-to-left/mod.js#L20-L36

![image](https://user-images.githubusercontent.com/16874139/90312248-377f0f00-df46-11ea-8bba-0b0c254397ac.png)

**Comment by Fahme** [comment]
@dragonwocky Thanks for your work my implementation in the PR is slightly more performant : 

https://stackoverflow.com/a/39332340/6938643 -> give this answer a read hope it will be helpful :)

**Comment by dragonwocky** [comment]
@Fahme did some performance work with a `requestAnimationFrame` debounce and getting rid of `querySelector`, thanks for the stackoverflow link. I didn't use your method, though, because it means only page content is aligned, whereas my updated code fixes #4 and does right-to-left alignment on fullpage databases and in search.

![image](https://user-images.githubusercontent.com/16874139/90325429-e2331400-dfbe-11ea-9a34-1f39e3d0b7fd.png)
![image](https://user-images.githubusercontent.com/16874139/90325430-e9f2b880-dfbe-11ea-9e57-507881166afd.png)

**Comment by Fahme** [comment]
@dragonwocky there's alot of things that needs to be done for the DB RTL support not only the text but also the buttons that overlay on text, table items, input items etc ..

probably will need to find a better way than currently to support and fix major issues in #8 as well or else this extension is not very practical for full RTL support IMO

**Comment by dragonwocky** [comment]
it's definitely not perfect, but it's better than nothing. the enhancer is all about improving notion in the ways it can until a better way appears. over time, improvements will be made until notion has support builtin.

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/
notion-enhancer v0.8 now released.

**Comment by alonidel** [comment]
Would be great to make the RTL support full.
In this example the bullets in the Hebrew text should be on the Right side of the text.

[
![Screen Shot 2020-08-28 at 17 30 24](https://user-images.githubusercontent.com/47115834/91579405-39889b00-e954-11ea-80e0-04bdd6a99ec8.png)
](url)

**Comment by obahareth** [comment]
@alonidel Are you sure you're on the latest version? This was resolved in #8.

**Comment by alonidel** [comment]
I'm on the latest notion-enhancer (Mac)

**Comment by dragonwocky** [comment]
@alonidel the version in notion-enhancer is extremely buggy at the moment, and though it was based on this currently has very different code. it's better to ask support for it in the notion-enhancer repo.

**Comment by dragonwocky** [comment]
I think this issue can be closed: I'm now using a more direct implementation of @Fahme's code, which works reliably and solves the above problem.

**Comment by obahareth** [comment]
@all-contributors please add @dragonwocky for platform contributions.

**Comment by DSparda** [comment]
Sorry guys can you guide me how to use RTL in Notion Enhanced in Linux ver ?
I have already enabled it in Enhancements but don't know how to use in app ...
